### PR TITLE
Various documentation fixes.

### PR DESCRIPTION
**Pull request by patternspandemic**
Greetings Pietro,

I've had a run through the docs correcting a number of spelling and grammatical errors, as well as a few areas where the docs referenced deprecated API usage.

Cheers,
Brad

### CODE REVIEW

**Comment by pietroalbini** [comment]
There is just that little thing to be fixed, but thank you so much for this PR!

*While I was reading the diff, I felt embarassed multiple times for some of the errors...*

**Comment by patternspandemic** [comment]
Alright, I think I've made [this bit about component names](https://github.com/patternspandemic/botogram/commit/54674587f94a88c3cd3411c4ec8fff13acccca8c#diff-7253e1b7f574e435799b3d06c10bc369R30) more clear.

> _While I was reading the diff, I felt embarrassed multiple times for some of the errors..._

Ha, no worries. There's a lot to be documented, and it's not at all as interesting as working on or with the code :) Since you have more pressing decisions to make about the code, and seen you've released it to PyPI, I thought I'd have a go through the docs.

Brad

**Comment by pietroalbini** [comment]
Again, thank you! Will be live with botogram 0.2.

**Comment by pietroalbini** [comment]
And it's live on the [development docs](https://botogram.pietroalbini.io/docs/dev/)!

**Pull request merged**
