### PR TITLE
Document upstream API classes.

### PR DESCRIPTION
**Pull request by tsculpt**
Hi Pietro!
Here is completed documentation for the upstream API classes.
Cheers, Brad

### CODE REVIEW

**Comment by pietroalbini** [comment]
Wow, that's huge! Thank you!

I just want to point out some things before merging this. If you don't have time to do these changes just notify me so I can do those for you:

* Mixins should be left as an implementation detail: they're just a way to share code easily between different objects. It's better if the methods' description is copied in each object.
* You can move EmptyObject to the main section, it doesn't need a section by its own.
* In the methods documentation, leave the `:param ...:`s section at the end of the method definition. This is also because when I finish an update to the documentation, that section will look slightly different.
* Also in the method documentation, try to follow the style I use for the few classes I documented: narrative introduction, narrative description of the parameters, definition with `:param ...:`s.
* It looks better if you don't use the brackets when you specify the type of an attribute: if it's an object in the documentation just use the `:ref:`, else wrap the type as a code thing (the one with two `` -- GitHub don't render that).

And you should add your ``Copyright (c) 2015 Brad ...`` on top of the file, it's mostly made by you :-)

**Comment by pietroalbini** [comment]
Reference to #9.

**Comment by tsculpt** [comment]
Hi Pietro,

Thanks for the review. I should be able to make your requested changes, and allow you to continue work on timers :)

I had decided to include the mixins as a way to reduce duplicated documentation between classes. But I agree it will be easier and less confusing for users to have the methods inline.

With regards to `EmptyObject`, is there a reason it needs to be exposed at all?

**Comment by pietroalbini** [comment]
Maybe I can remove it completly, let me test something out.

**Comment by pietroalbini** [comment]
You're right, they weren't used, I removed them in 579c6c1. ``one_of`` was needed before the switch to the ``Chat`` object, and I don' t remember why I introduced EmptyObject...

**Comment by tsculpt** [comment]
Very good. One thing I noticed missing with regards to the upstream API were methods to send/reply/forward various other types (Audio, Document, Sticker, Video, Voice, and Location). Are these to be integrated into the existing Chat and Message mixins?

Last, the `extra` parameter of various messaging methods is not very descriptive of the reply interface option object it receives. That is, unless the parameter is due to receive other objects as well?

**Comment by pietroalbini** [comment]
Yes, those methods will be integrated in the future. I'll do that when I finish working on timers.

The `extra` parameter should receive only `ReplyKeyboardMarkup`, `ReplyMarkupHide` and `ForceReply`. What do you mean?

**Comment by tsculpt** [comment]
I mean to say its name should perhaps be changed to `reply_interface`, or `reply_extra`, or the like to indicate some idea of its purpose. As it stands, I feel like it could accept a file object or something else. For me it was just very general and required looking at the docs to get any idea of what it's for.

**Comment by tsculpt** [comment]
Alright. I believe all your requested changes have been made. Please have another look.
Cheers

**Comment by pietroalbini** [comment]
Live [in the docs](http://botogram.pietroalbini.io/docs/dev/api/telegram/) right now! Thank you for this PR.

**Pull request merged**
