### PR TITLE
Fix on some translations

### PR DESCRIPTION
**Pull request by possebon**
There was some mistyping messages. I fixed them today.

### CODE REVIEW

**Comment by possebon** [comment]
I also added Portuguese translation. There are little changes between Brazilian Portuguese and Portuguese, so I changed the file and created a new one.

**Comment by pietroalbini** [comment]
Can you please rebase your branch on master? There are conflicts right now.

**Comment by pietroalbini** [comment]
Any news on this @possebon?

**Comment by pietroalbini** [comment]
Merged manually to get this into the 0.5 release.

**Pull request merged**
